### ISSUE TITLE
Issue in console of px-simple-win-loss-chart

### ISSUE THREAD

**Issue by anundinesh** [PredixDev/px-simple-win-loss-chart#1]
We are getting "NaN" in the SVG parameter of y. I'm using Chrome browser. Could you please check the below issue?
![simple win loss chart](https://cloud.githubusercontent.com/assets/20392598/23652623/8f55d6aa-0321-11e7-882e-1a6f7196e4bf.png)

**Comment by randyaskin** [comment]
I'm not sure what changed, but I'm not seeing this issue in recent versions of the component. Reopen if you see it happening again.
